# Generated by Django 5.2.17 on 2026-09-25 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_boost_id', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('content_hash', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sync_state', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('stale', 'Stale'), ('missing', 'Missing')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('payload_hash', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('blocked', 'Blocked'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('completion_criteria', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('blocked', 'Blocked'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.directive')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('user', 'User'), ('web_client', 'Web client'), ('gateway', 'Gateway'), ('worker', 'Worker'), ('monitor', 'Monitor'), ('curator', 'Booster curator'), ('locutus', 'Locutus')], max_length=32)),
                ('nostr_pubkey', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('offline', 'Offline'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='core.account')),
                ('parent', models.ForeignKey(blank=True, help_text='Workers point at their gateway principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.principal')),
            ],
        ),
        migrations.CreateModel(
            name='PairingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('web_client', 'Web client'), ('gateway', 'Gateway'), ('worker', 'Worker')], max_length=16)),
                ('device_pubkey', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('poll_token', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, help_text='Filled when an authenticated client approves the request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing_requests', to='core.account')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_requests', to='core.principal')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_notes', to='core.account')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_notes', to='core.principal')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(blank=True, max_length=200)),
                ('endpoints', models.JSONField(blank=True, default=list, help_text='Reachable worker API URLs, e.g. Docker DNS, VPC IP, or server relay.')),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('approval_policy', models.JSONField(blank=True, default=dict)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='core.principal')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=80)),
                ('subject_type', models.CharField(blank=True, max_length=80)),
                ('subject_id', models.CharField(blank=True, max_length=80)),
                ('public_metadata', models.JSONField(blank=True, default=dict)),
                ('encrypted_payload', models.BinaryField(blank=True, null=True)),
                ('nostr_event_id', models.CharField(blank=True, max_length=128)),
                ('signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.account')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.principal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='directive',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directives', to='core.principal'),
        ),
        migrations.CreateModel(
            name='BoosterProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_change', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_proposals', to='core.account')),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booster_proposals', to='core.approvalrequest')),
                ('booster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='core.booster')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_proposals', to='core.principal')),
            ],
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.principal'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=16)),
                ('nostr_signature', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.approvalrequest')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.principal')),
            ],
        ),
        migrations.CreateModel(
            name='AccountMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technocore_memberships', to=settings.AUTH_USER_MODEL)),
                ('principal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='core.principal')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('signing', 'Signing'), ('encryption', 'Encryption')], max_length=16)),
                ('public_key', models.CharField(max_length=256)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='core.principal')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_ref', models.CharField(max_length=500)),
                ('default_branch', models.CharField(default='main', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('secret', 'Secret'), ('booster', 'Booster'), ('collection', 'Collection'), ('repository', 'Repository'), ('mcp_connection', 'MCP connection'), ('memory', 'Hammerspace')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.account')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_resources', to='core.principal')),
            ],
        ),
        migrations.CreateModel(
            name='KeyEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_version', models.PositiveIntegerField()),
                ('wrapped_data_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_envelopes', to='core.principal')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='InfraResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('application', 'Application'), ('service', 'Service'), ('environment', 'Environment'), ('server', 'Server'), ('database', 'Database'), ('storage', 'Storage'), ('domain', 'Domain'), ('dns_record', 'DNS record'), ('certificate', 'Certificate'), ('deployment', 'Deployment')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('environment', models.CharField(blank=True, max_length=32)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('desired_state', models.JSONField(blank=True, default=dict)),
                ('observed_state', models.JSONField(blank=True, default=dict)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('cost_cents_monthly', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_resources', to='core.account')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infra_resources', to='core.project')),
                ('credential_resource', models.ForeignKey(blank=True, help_text='Encrypted credential used to manage this resource. Never plaintext.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infra_bindings', to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=8)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_given', to='core.principal')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.principal')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('algorithm', models.CharField(default='xchacha20poly1305', max_length=64)),
                ('content_version', models.PositiveIntegerField(default=1)),
                ('content_hash', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_object', to='core.resource')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_members', to='core.resource')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='core.resource')),
            ],
        ),
        migrations.AddField(
            model_name='booster',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booster', to='core.resource'),
        ),
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('trigger', models.CharField(blank=True, max_length=200)),
                ('instructions', models.TextField()),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_orders', to='core.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standing_orders', to='core.principal')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('done', 'Done'), ('failed', 'Failed'), ('released', 'Released')], default='open', max_length=16)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, to='core.task')),
                ('directive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.directive')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='HumanAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('instructions', models.TextField()),
                ('verification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('deferred', 'Deferred'), ('expired', 'Expired')], default='requested', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_actions', to='core.account')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_actions', to='core.principal')),
                ('blocks_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_actions', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hull', models.CharField(choices=[('local_module', 'Local module'), ('cloud_ship', 'Cloud ship')], default='local_module', max_length=32)),
                ('runtime_state', models.CharField(choices=[('starting', 'Starting'), ('ready', 'Ready'), ('busy', 'Busy'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='starting', max_length=16)),
                ('container_ref', models.CharField(blank=True, max_length=200)),
                ('capability_manifest', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='core.gateway')),
                ('principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='core.principal')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.worker'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('directive', 'version'), name='uniq_plan_version'),
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['account', 'kind'], name='core_princi_account_e45920_idx'),
        ),
        migrations.AddIndex(
            model_name='principal',
            index=models.Index(fields=['status'], name='core_princi_status_0e049a_idx'),
        ),
        migrations.AddIndex(
            model_name='pairingrequest',
            index=models.Index(fields=['status', 'expires_at'], name='core_pairin_status_bea53e_idx'),
        ),
        migrations.AddIndex(
            model_name='memorynote',
            index=models.Index(fields=['account', 'created_at'], name='core_memory_account_4e85db_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['account', 'created_at'], name='core_event_account_b8cda7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['account', 'type'], name='core_event_account_1fbea2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['subject_type', 'subject_id'], name='core_event_subject_3e9ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['account', 'status'], name='core_approv_account_1756fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountmembership',
            constraint=models.UniqueConstraint(fields=('account', 'user'), name='uniq_account_user'),
        ),
        migrations.AddConstraint(
            model_name='principalkey',
            constraint=models.UniqueConstraint(fields=('principal', 'purpose', 'version'), name='uniq_principal_key_version'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('account', 'slug'), name='uniq_account_project_slug'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['account', 'kind'], name='core_resour_account_ec2170_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyenvelope',
            constraint=models.UniqueConstraint(fields=('resource', 'content_version', 'recipient'), name='uniq_envelope_recipient_version'),
        ),
        migrations.AddIndex(
            model_name='infraresource',
            index=models.Index(fields=['account', 'kind', 'environment'], name='core_infrar_account_19b9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['principal', 'effect'], name='core_grant_princip_949d34_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionmember',
            constraint=models.UniqueConstraint(fields=('collection', 'resource'), name='uniq_collection_resource'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'lease_expires_at'], name='core_task_status_811981_idx'),
        ),
    ]
