# Generated by Django 5.2.17 on 2026-09-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingrequest',
            name='encryption_pubkey',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
