// Package pisoconfig resolves piso project/dir/gateway paths and the compose
// files the CLI drives. Kept free of Docker logic so the CLI stays testable.
package pisoconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// Project is a resolved piso workspace: the host dir mounted into the worker.
type Project struct {
	Dir  string // absolute host dir mounted at /workspace
	Slug string // safe container/compose name derived from dir
}

// Resolve builds a Project from an absolute directory.
func Resolve(dir string) (Project, error) {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return Project{}, err
	}
	st, err := os.Stat(abs)
	if err != nil {
		return Project{}, err
	}
	if !st.IsDir() {
		return Project{}, fmt.Errorf("%s is not a directory", abs)
	}
	return Project{Dir: abs, Slug: slug(abs)}, nil
}

// ProjectFromCWD resolves the project from the current working directory.
func ProjectFromCWD() (Project, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return Project{}, err
	}
	return Resolve(cwd)
}

// slug converts a workspace path into a safe identifier.
func slug(dir string) string {
	base := filepath.Base(dir)
	// strip unsafe characters
	re := regexp.MustCompile(`[^a-zA-Z0-9_.-]+`)
	base = re.ReplaceAllString(base, "-")
	base = strings.Trim(base, "-.")
	if base == "" || base == "." {
		base = "workspace"
	}
	return base
}

// WorkerName is the deterministic container name (must match the compose
// template's container_name).
func (p Project) WorkerName() string { return "piso-worker-" + p.Slug }

// GatewayCompose returns the path to the shared gateway compose file.
func GatewayCompose() (string, error) {
	// prefer repo compose; fall back to the installed location
	candidates := []string{
		filepath.Join("compose", "gateway.yaml"),
		filepath.Join(runtimePath(), "compose", "gateway.yaml"),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c, nil
		}
	}
	return candidates[0], nil
}

// WriteWorkerCompose renders the worker compose template with this project's
// values into .piso/worker-<slug>.yaml relative to the project dir.
func WriteWorkerCompose(p Project) (string, error) {
	tmpl, err := findTemplate()
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(tmpl)
	if err != nil {
		return "", err
	}
	repoRoot := runtimePath()
	out := string(data)
	out = strings.ReplaceAll(out, "PROJ-SLUG", p.Slug)
	out = strings.ReplaceAll(out, "PROJECT_DIR", p.Dir)
	out = strings.ReplaceAll(out, "WORKER_BUILD_CONTEXT", filepath.Join(repoRoot, "worker"))
	// The CA is generated by the shared gateway into the REPO's .piso dir
	// (the gateway runs from the repo), not the project's.
	out = strings.ReplaceAll(out, "CA_DIR", filepath.Join(repoRoot, ".piso"))
	out = strings.ReplaceAll(out, "GATEWAY_CONTROL", GatewayURL())

	pisoDir := filepath.Join(p.Dir, ".piso")
	if err := os.MkdirAll(pisoDir, 0o700); err != nil {
		return "", err
	}
	dest := filepath.Join(pisoDir, "worker-"+p.Slug+".yaml")
	if err := os.WriteFile(dest, []byte(out), 0o600); err != nil {
		return "", err
	}
	return dest, nil
}

func findTemplate() (string, error) {
	candidates := []string{
		filepath.Join("compose", "worker.yaml.tmpl"),
		filepath.Join(runtimePath(), "compose", "worker.yaml.tmpl"),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c, nil
		}
	}
	return "", fmt.Errorf("worker compose template not found (run from the piso repo or install it)")
}

// runtimePath returns the piso repo root (dir of the go.mod file's parent
// would be nicer; this is the dir above cli/).
func runtimePath() string {
	exe, err := os.Executable()
	if err != nil {
		return "."
	}
	// exe lives in <root>/bin or <root>/cli/bin; walk up looking for go.mod
	dir := filepath.Dir(exe)
	for i := 0; i < 5; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "."
}

// GatewayURL is the control-plane base URL (override with PISO_GATEWAY).
func GatewayURL() string {
	if v := os.Getenv("PISO_GATEWAY"); v != "" {
		return strings.TrimRight(v, "/")
	}
	return "http://127.0.0.1:8081"
}

// API shapes mirror the gateway's model (safe on the client side; the
// gateway never sends real secret values over GET).
type SecretSummary struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Placeholder  string   `json:"placeholder"`
	AllowedHosts []string `json:"allowedHosts"`
}

type SecretIn struct {
	Name         string   `json:"name"`
	Placeholder  string   `json:"placeholder"`
	Value        string   `json:"value"`
	AllowedHosts []string `json:"allowedHosts"`
}

type RouteIn struct {
	Name   string `json:"name"`
	Worker string `json:"worker"`
	Port   int    `json:"port"`
}

type LogRecord struct {
	ID       string    `json:"id"`
	Worker   string    `json:"worker"`
	Ts       time.Time `json:"ts"`
	Method   string    `json:"method"`
	Scheme   string    `json:"scheme"`
	Host     string    `json:"host"`
	Path     string    `json:"path"`
	Status   int       `json:"status"`
	Action   string    `json:"action"`
	Reasons  []string  `json:"reasons"`
	Findings []Finding `json:"findings"`
}

type Finding struct {
	Kind string `json:"kind"`
}